### ISSUE TITLE
不是吐槽 是真的想骂，这华为的导航栏真的一言难尽

### ISSUE THREAD

**Issue by lijiajunios** [ausboyue/Wechat_HarmonyOS#2]
不是吐槽 是真的想骂，这华为的导航栏真的一言难尽，这么大的公司，导航栏、状态栏，写的都是啥，一堆垃圾，对比苹果的导航栏和状态栏，有的时候你不得不佩服人家的设计，对开发友好，对使用人也友好

**Comment by ausboyue** [comment]
api9的状态栏确实一言难尽，更高的api做了很多优化，由于我身边暂没有高api的设备，所以暂无法做开发和调试哈

**Comment by ausboyue** [comment]
最新版(api 12)的状态栏表现还是不错的
