### ISSUE TITLE
跑不起来呢 

### ISSUE THREAD

**Issue by LGByte** [ausboyue/Wechat_HarmonyOS#3]
![Uploading 截屏2024-07-17 10.13.32.png…]()
报错

**Comment by LGByte** [comment]
![Uploading 截屏2024-07-17 10.13.32.png…]()

**Comment by LGByte** [comment]
<img width="321" alt="截屏2024-07-17 10 15 24" src="https://github.com/user-attachments/assets/719e349f-8dec-45c5-9a93-0053f0876d4e">

**Comment by LGByte** [comment]
<img width="843" alt="截屏2024-07-17 10 17 35" src="https://github.com/user-attachments/assets/fe8696ac-389b-420e-b007-181780e7eb44">

**Comment by ausboyue** [comment]
> <img alt="截屏2024-07-17 10 17 35" width="843" src="https://private-user-images.githubusercontent.com/16233021/349334964-fe8696ac-389b-420e-b007-181780e7eb44.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExODQ1ODMsIm5iZiI6MTcyMTE4NDI4MywicGF0aCI6Ii8xNjIzMzAyMS8zNDkzMzQ5NjQtZmU4Njk2YWMtMzg5Yi00MjBlLWIwMDctMTgxNzgwZTdlYjQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE3VDAyNDQ0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmMzA3MDJiMzQzYzgxYmYxODBjMGNmNWU0MTUxMDUyMmJhODdmYjM1NjJjODE3YjAyMWNiZDY0Y2RiMTkwYTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cdMj8Cmo2SGmLU6YvKq7IvZ_H-eLdvt8rYUuhNQLgaQ">

目前代码已经升级api12了，需要DevEco 5.0+鸿蒙Next系统真机或模拟器才可以跑得起来，DevEco 5.0鸿蒙官网已经支持下载安装了，没真机的话，可以在DevEco 5.0里下载鸿蒙Next模拟器(需要开发工具里完成华为账号登录并完成next模拟器申请，快的话10分钟搞定，慢的话几小时就好，依据审核速度)去运行，可以升级下试试。

**Comment by LGByte** [comment]
我已经是最新的5.0的了，next 版本的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 皓 煙 、 ***@***.***&gt;
发送时间: 2024年7月17日 10:52
收件人: ausboyue/Wechat_HarmonyOS ***@***.***&gt;
抄送: LGByte ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [ausboyue/Wechat_HarmonyOS] 跑不起来呢  (Issue #3)

**Comment by ausboyue** [comment]
> 我已经是最新的5.0的了，next 版本的 发自我的iPhone

你这个看起来项目都没加载好，连”entry“的module都没加载得出来，建议重新下载项目并导入试试（一切保持默认）。我刚刚试了重新下载项目并打开，运行都是没问题的。我的DevEco版本： 5.0.3.404  ，另外请确保OpenHarmony SDK的api11及以上版本的arkts和toolchains安装。
